### ISSUE TITLE
No @Mockery annotation for param was found

### ISSUE THREAD

**Issue by marco-manza** [VictorAlbertos/Mockery#7]
I have an interface defined like this;

```
    @POST ("api/v1/user/login")
    @DTOArgs(UserMock.class)
    Observable<User> login(@Body LoginWrapper wrapper);
```

And I get the following error:

> Error:error: When checking method
> No @Mockery annotation for param wrapper was found.
> To fix it, annotate this param with one.

I don't understand why I have to add some Mockery annotation to the request body.
I just want to have the response mocked.

I know I can add @Optional to make it work, buy why should I do so? I would like to avoid that to keep the interface as clean as possible

**Comment by VictorAlbertos** [comment]
Because Mockery is not only for mocking data, it is designed too to provide a way to automate unit testing for the network layer. That's why the annotation is required.
