### ISSUE TITLE
Android apt plugin is incompatible with the Android Gradle plugin.

### ISSUE THREAD

**Issue by Tan-Tshunglee** [VictorAlbertos/Mockery#9]
### My project Gradle version
4.1

### My project Android Gradle plugin version
3.0.1

after I add below line to root project buildscript  dependencies block
`classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'`

Gradle give me following error message:
Error:android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.

**Comment by VictorAlbertos** [comment]
This issue is not related at all with Mockery.

https://stackoverflow.com/questions/42574803/incompatible-plugins-for-android-apt-after-upgrading-to-android-studio-2-3

**Comment by Tan-Tshunglee** [comment]
Sorry, apt plugin 'com.neenbedankt.gradle.plugins:android-apt:1.8' is not incompatible with the gradle android plugin v3.0 but the v2.3.
